### ISSUE TITLE
Невозможно ввести текст в поле Название состоящий только из английского языка

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#20]
**Фактический результат:**
![Веб](https://github.com/azawert/modji-frontend/assets/140902759/fbfb41f6-f876-4b71-87dc-ae7dc6842c84)

**Ожидаемый результат:**
В поле возможно ввести только английские буквы
![Веб](https://github.com/azawert/modji-frontend/assets/140902759/7ae996a1-c120-48ea-bce2-e6fcc7e5a8a2)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/35
