### ISSUE TITLE
Цвет рамки Номер комнаты не становится красным после ввода уже существующего номера

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#28]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/230b070b-8fbf-4c78-82f1-8a4ec746e0a0)

**Ожидаемый результат:**
Рамка поля после ввода существующего номера станет красной и под полем появится текст "Комната с таким номером уже существует в системе"
![Веб](https://github.com/user-attachments/assets/5c2dd795-d03e-4973-9b69-998305bd60e1)

**Comment by azawert** [comment]
исправлено в рамках https://github.com/azawert/modji-frontend/pull/13
