### ISSUE TITLE
В поле площадь невозможно ввести больше 4 символов

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#29]
https://github.com/user-attachments/assets/fdc56a84-c48d-454b-b375-3a0b97b9a725

**Ожидаемый результат**
В поле Площадь возможно ввести 6 символов
![Веб](https://github.com/user-attachments/assets/94f8cf13-b442-46c6-859b-8ae5be34e2b2)

**Comment by azawert** [comment]
Технически реализовано так, чтобы была возможность ввести 4 цифры и 2 цифры после запятой
Пока оставляем так
