### ISSUE TITLE
Результат удаления информации в поле Площадь не сохраняется после редактирования

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#31]
**Фактический результат:**

https://github.com/user-attachments/assets/c9edc68a-0689-4780-ba5d-4a0746ab4315

**Ожидаемый результат:**
При редактировании информации в поле Площадь результат сохраняется в любом случае

**Comment by azawert** [comment]
при вызове реста на обновление комнаты, передается такой запрос
{"categoryId":48,"number":"ввв","area":null,"description":"яблочко"}
area = null
ответ возвращается такого вида:
{
    "id": 22,
    "number": "ввв",
    "area": 14.0,
    "categoryDto": {
        "id": 48,
        "name": "три",
        "description": ""
    },
    "description": "яблочко",
    "isVisible": true
}
"area": 14.0 - видимо на беке значение не перезатирается, если area = null
