### ISSUE TITLE
Ранее выбранное значение имеет окрашивание при раскрытии выпадающего списка

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#32]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/743afade-7bc6-4e10-96c8-1f43693a953e)

**Ожидаемый результат:**
Ранее выбранная строка не имеет подсветки после повторного раскрытия выпадающего списка
![Веб](https://github.com/user-attachments/assets/e0025309-fed0-4fa3-8038-0de0b76479ef)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/35
