### ISSUE TITLE
Выпадающий список не имеет полосы прокрутки при количестве значений больше 5

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#33]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/743afade-7bc6-4e10-96c8-1f43693a953e)

**Ожидаемый результат:**
В выпадающем списке появляется возможность прокрутки при количестве значений больше 5

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/35
