### ISSUE TITLE
У карточек категорий номеров при наведении не появляется рамка

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#34]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/05e5c531-510f-4901-9a9e-8405b7cbdb14)

**Ожидаемый результат:**
При наведении у карточки категории появляется рамка цвета #D5E1FF
![Веб](https://github.com/user-attachments/assets/e73a486d-8280-4a95-a50b-6973ef1340df)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/35
