### ISSUE TITLE
Кнопки для строки управляющего не выровнены по правому краю

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#37]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/500ccc1a-d969-4a81-a0b0-81c2dfe21711)

**Ожидаемый результат:**
![Веб](https://github.com/user-attachments/assets/d7933e5b-5ea7-49b0-87e3-bcd889353a24)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/50
