### ISSUE TITLE
Строка сотрудника не раскрывается при нажатии на неё

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#39]
**Фактический результат:**
Строка неактивна

**Ожидаемый результат:**
Строка сотрудника активна, при нажатии на неё раскрывается полная информация
(Для номеров, строка, скорее всего, должна работать также)
![Веб](https://github.com/user-attachments/assets/41d09182-7c16-4694-9c55-e8404d39722f)
![Веб](https://github.com/user-attachments/assets/e734990b-58d6-4342-93de-f3bd2a07ac00)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/50
