### ISSUE TITLE
Тень краёв таблицы не соответствует макету

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#40]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/2de9c640-55fd-49eb-b1c6-1da9e0650726)

**Ожидаемый результат:**
box-shadow: 0px 4px 8px 0px;
![Веб](https://github.com/user-attachments/assets/befbf7d8-5cd5-4585-948d-529d566e7ae9)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/50
