### ISSUE TITLE
Поле Должность заполнено в дефолтном состоянии

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#41]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/542bc83a-a148-492a-a447-d3f2abf09bd1)

**Ожидаемый результат:**
Поле с выпадающим списком в дефолтном состоянии имеет плейсхолдер
![Веб](https://github.com/user-attachments/assets/2d7302f8-f4d7-49e3-81fa-1c649eb12743)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/50
