### ISSUE TITLE
Текст ошибки под полем не выровнен с текстом введённым в поле

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#42]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/88a3a297-b3cb-40ed-93b5-467ccbbfbbf8)

**Ожидаемый результат:**
Текст ошибки выровнен с введённым текстом
![Веб](https://github.com/user-attachments/assets/c06872ce-0a05-4d3a-84f4-3d2947688037)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/50
