### ISSUE TITLE
Окно Сотрудник с таким адресом электронной почты уже существует в системе не имеет ссылки сотрудника

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#43]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/0910ef36-137e-469b-82e5-63edcd6fe891)

**Ожидаемый результат:**
Окно Сотрудник с таким адресом электронной почты уже существует в системе имеет ссылку на сотрудника
![Веб](https://github.com/user-attachments/assets/cc5a7869-1fca-4056-b609-affc4ac98fd5)

**Comment by azawert** [comment]
Не будет реализовано
