### ISSUE TITLE
Рамка поля Пароль повторно* не изменяет цвет на красный при несовпадении паролей

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#44]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/f945e98d-51c3-412d-9385-5c069bbbfec7)

**Ожидаемый результат:**
Рамка поля Пароль повторно* станет красной при несовпадении паролей
![Веб](https://github.com/user-attachments/assets/093b95f6-db97-4f6a-9cc0-6f59f0510ecc)

**Comment by azawert** [comment]
не воспроизводится
![image](https://github.com/user-attachments/assets/d0e320cf-74a7-4d2c-862a-a327e485352b)
