### ISSUE TITLE
В поле Отчество можно ввести больше 15 символов

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#45]
**Фактический результат:**
В поле Отчество можно ввести до 30 символов
![Веб](https://github.com/user-attachments/assets/c7c29720-1e11-4262-984b-4f55d110dcb4)

**Ожидаемый результат:**
В поле Отчество можно ввести не больше 15 символов
![Веб](https://github.com/user-attachments/assets/b21ee2c7-3910-48fb-9500-2bee5d901ffa)

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/50
