### ISSUE TITLE
Невозможно ввести 1 символ в доменной части электронной почты после точки

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#47]
**Фактический результат:**
![Веб](https://github.com/user-attachments/assets/8e8d7277-e9e9-4fb2-a676-14f5fc1257be)

**Ожидаемый результат:**
В доменной части электронной почты после точки можно ввести 1 символ

**Comment by azawert** [comment]
Для проверки паттерна ввода емейла используется базовое регулярное выражение, которое не дает ввести 1 символ после точки, потому что это не будет валидной почтой
