### ISSUE TITLE
Окно Сотрудник с таким адресом электронной почты уже существует в системе не появляется при редактировании сотрудника

### ISSUE THREAD

**Issue by KalinichenkoMaria** [azawert/modji-frontend#49]
**Фактический результат:**
При нажатии на кнопку Сохранить с использованием уже имеющийся в БД почты не появляется окно Сотрудник с таким адресом электронной почты уже существует в системе

https://github.com/user-attachments/assets/b32f0e83-1c7b-4409-8932-a28688cf9c18

**Ожидаемый результат:**
Окно Сотрудник с таким адресом электронной почты уже существует в системе появляется при редактировании

**Comment by azawert** [comment]
https://github.com/azawert/modji-frontend/pull/50
